spring.application.name=JpaHibernative
spring.datasource.url=jdbc:postgresql://localhost/fatec
spring.datasource.username=postgres
spring.datasource.password=Cleison23!08
server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update